//After user logins
//they should be accessed to those routes where they are permitted to
//So we need jwtAuth for that
//So jwt middleware verifies the token generated by the user so thatthey can have privilage
require("dotenv").config();
const jwt = require("jsonwebtoken");

const jwtAuth = (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;

    if (!authHeader) {
      return res.status(401).json({ message: "Authorization header missing" });
    }

    const [type, token] = authHeader.split(" ");

    if (type !== "Bearer" || !token) {
      return res.status(401).json({ message: "Invalid token format" });
    }

    const decoded = jwt.verify(token, process.env.JWT_SECRET);

    req.user = decoded; // { userId, role, iat, exp }
    // console.log(req.user)
    next();
  } catch (err) {
    return res.status(401).json({ message: "Invalid or expired token" });
  }
};

module.exports = jwtAuth;
